# Central Snakemake for digestiflow_demux.

import os

from digestiflow_demux.snakemake_support import (
    bcl2fastq_wrapper,
    get_result_files_fastqc,
    get_result_files_demux,
    get_tiles_arg,
    wrapper_path,
)

# -------------------------------------------------------------------------------------------------
# Helper Function


def out_prefix(path):
    return os.path.join(config["output_dir"], path)

# -------------------------------------------------------------------------------------------------
# Define local rules.

localrules: all, marker_file

# -------------------------------------------------------------------------------------------------
# The main rule depends on the "result is complete" file.

rule all:
    input: out_prefix("DIGESTIFLOW_DEMUX_DONE.txt"),

# -------------------------------------------------------------------------------------------------
# Create "result is complete" file.

rule marker_file:
    input:
        out_prefix("multiqc/multiqc_report.html"),
        out_prefix("multiqc/multiqc_data.zip"),
        # **get_result_files_fastqc(config),
    output: out_prefix("DIGESTIFLOW_DEMUX_DONE.txt"),
    shell:
        r"""
        set -x; date --iso-8601=s >{output}
        """

# -------------------------------------------------------------------------------------------------
# Perform demultiplexing.

rule demux:
    input: out_prefix("SampleSheet.csv")
    output: get_result_files_demux(config)
    params:
        flowcell_token=config["flowcell"]["vendor_id"],
        input_dir=config["input_dir"],
        output_dir=config["output_dir"],
        tiles_arg=get_tiles_arg(config),
    threads: config["cores"]
    wrapper: wrapper_path(bcl2fastq_wrapper(config))

# -------------------------------------------------------------------------------------------------
# Run FastQC.

rule fastqc:
    input:
        fastq=out_prefix("{sample}/{flowcell}/{lane}/{filename}.fastq.gz")
    output:
        html=out_prefix("{sample}/{flowcell}/{lane}/qc/fastqc/{filename}_fastqc.html"),
        html_md5=out_prefix("{sample}/{flowcell}/{lane}/qc/fastqc/{filename}_fastqc.html.md5"),
        zip=out_prefix("{sample}/{flowcell}/{lane}/qc/fastqc/{filename}_fastqc.zip"),
        zip_md5=out_prefix("{sample}/{flowcell}/{lane}/qc/fastqc/{filename}_fastqc.zip.md5"),
    threads: 1
    wrapper: wrapper_path("fastqc")

# -------------------------------------------------------------------------------------------------
# Collect all QC statistics using MultiQC.

rule illumina_demultiplexing_multiqc:
    input: get_result_files_fastqc(config)["zip"]
    output:
        html=out_prefix("multiqc/multiqc_report.html"),
        zip=out_prefix("multiqc/multiqc_data.zip"),
    threads: 1
    wrapper: wrapper_path("multiqc")
